server:
  port: 8081
  servlet:
    session:
      cookie:
        name: CASHFLOWSESSIONID
spring:
  application:
    name: cashflow
  datasource:
    url: jdbc:h2:file:./var/cashflow.h2
    username: sa
    password: ""
